import React from 'react'

// eslint-disable-next-line
export default props =>
<table>
  <thead>
    <tr>
      <th>Categoria</th>
      <th>Valor</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    <tr>
      <td>gasolina</td>
      <td>178.99</td>
    </tr>
    
  </tbody>
</table>